language: python
sudo: required

services:
  - docker

before_install:
  - git submodule update --init --recursive
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - cp ./Dockerfile certbot/Dockerfile

install:
  - docker build --rm --no-cache -t stevebargelt/certbot-rpi certbot/
  - docker push stevebargelt/certbot-rpi
  - docker tag stevebargelt/certbot-rpi stevebargelt/letsencrypt-rpi
  - docker push stevebargelt/letsencrypt-rpi

script: true
notifications:
  slack:
    rooms:
      - bargelt:r8ZuK4YKz8rPmOfPZ07pFF49#general
    template:
      - "Status=%{result}, Job=%{repository_name}, Build=%{build_number}, URL=%{build_url}, HUB=https://hub.docker.com/r/stevebargelt/certbot-rpi/"